/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Wiener_FilterC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fe5e079880f10d2a905dac77a7fa83d8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/outoftree/Wiener_FilterC.h>
// pydoc.h is automatically generated in the build directory
#include <Wiener_FilterC_pydoc.h>

void bind_Wiener_FilterC(py::module& m)
{

    using Wiener_FilterC    = ::gr::outoftree::Wiener_FilterC;


    py::class_<Wiener_FilterC, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Wiener_FilterC>>(m, "Wiener_FilterC", D(Wiener_FilterC))

        .def(py::init(&Wiener_FilterC::make),
           py::arg("window_size"),
           D(Wiener_FilterC,make)
        )
        




        
        .def("set_Window_Size",&Wiener_FilterC::set_Window_Size,       
            py::arg("window_size"),
            D(Wiener_FilterC,set_Window_Size)
        )


        
        .def("Window_Size",&Wiener_FilterC::Window_Size,       
            D(Wiener_FilterC,Window_Size)
        )

        ;




}








