/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Z_ScoreC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c04e7645056e72e6e785dfff7d44ff0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/outoftree/Z_ScoreC.h>
// pydoc.h is automatically generated in the build directory
#include <Z_ScoreC_pydoc.h>

void bind_Z_ScoreC(py::module& m)
{

    using Z_ScoreC    = ::gr::outoftree::Z_ScoreC;


    py::class_<Z_ScoreC, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Z_ScoreC>>(m, "Z_ScoreC", D(Z_ScoreC))

        .def(py::init(&Z_ScoreC::make),
           D(Z_ScoreC,make)
        )
        



        ;




}








